/* ------------------------------------------------------------------ */
/*  MC-553 — Mock activity, alerts, stats for Control Plane Dashboard */
/* ------------------------------------------------------------------ */

import type { ActivityEvent, DashboardAlert, SummaryStats } from "./dashboard-types";

function hoursAgo(h: number): string {
  return new Date(Date.now() - h * 3_600_000).toISOString();
}

function minutesAgo(m: number): string {
  return new Date(Date.now() - m * 60_000).toISOString();
}

export const MOCK_ACTIVITY: ActivityEvent[] = [
  {
    id: "evt-01",
    timestamp: minutesAgo(1),
    agentId: "agent-naomi",
    agentName: "Naomi",
    agentInitials: "NN",
    eventType: "agent.task.completed",
    description: "Completed task: Style filter dropdown",
    storyKey: "MC-537",
  },
  {
    id: "evt-02",
    timestamp: minutesAgo(4),
    agentId: "agent-james",
    agentName: "James",
    agentInitials: "JH",
    eventType: "agent.planning.started",
    description: "Started planning for dispatch queue story",
    storyKey: "MC-540",
  },
  {
    id: "evt-03",
    timestamp: minutesAgo(12),
    agentId: "agent-naomi",
    agentName: "Naomi",
    agentInitials: "NN",
    eventType: "agent.task.started",
    description: "Started task: Implement drag-drop reorder",
    storyKey: "MC-537",
  },
  {
    id: "evt-04",
    timestamp: minutesAgo(18),
    agentId: "agent-amos",
    agentName: "Amos",
    agentInitials: "AM",
    eventType: "agent.pr.opened",
    description: "Opened PR #172 for contract tests",
    storyKey: "MC-535",
  },
  {
    id: "evt-05",
    timestamp: minutesAgo(19),
    agentId: "agent-amos",
    agentName: "Amos",
    agentInitials: "AM",
    eventType: "agent.review.requested",
    description: "Requested review for MC-535",
    storyKey: "MC-535",
  },
  {
    id: "evt-06",
    timestamp: minutesAgo(25),
    agentId: "agent-naomi",
    agentName: "Naomi",
    agentInitials: "NN",
    eventType: "agent.task.completed",
    description: "Completed task: Add hover transitions to cards",
    storyKey: "MC-537",
  },
  {
    id: "evt-07",
    timestamp: minutesAgo(38),
    agentId: "agent-amos",
    agentName: "Amos",
    agentInitials: "AM",
    eventType: "agent.execution.completed",
    description: "All tasks completed for MC-535",
    storyKey: "MC-535",
  },
  {
    id: "evt-08",
    timestamp: minutesAgo(45),
    agentId: "agent-james",
    agentName: "James",
    agentInitials: "JH",
    eventType: "agent.assignment.dispatched",
    description: "Dispatched MC-540 to James",
    storyKey: "MC-540",
  },
  {
    id: "evt-09",
    timestamp: minutesAgo(46),
    agentId: "agent-james",
    agentName: "James",
    agentInitials: "JH",
    eventType: "agent.assignment.accepted",
    description: "James accepted assignment for MC-540",
    storyKey: "MC-540",
  },
  {
    id: "evt-10",
    timestamp: minutesAgo(60),
    agentId: "agent-alex",
    agentName: "Alex",
    agentInitials: "AR",
    eventType: "agent.execution.completed",
    description: "Completed research spike on caching strategy",
    storyKey: "MC-530",
  },
  {
    id: "evt-11",
    timestamp: minutesAgo(72),
    agentId: "agent-alex",
    agentName: "Alex",
    agentInitials: "AR",
    eventType: "agent.session.stale",
    description: "Session idle — no new assignments",
    storyKey: null,
  },
  {
    id: "evt-12",
    timestamp: minutesAgo(90),
    agentId: "agent-naomi",
    agentName: "Naomi",
    agentInitials: "NN",
    eventType: "agent.task.completed",
    description: "Completed task: Refactor card component",
    storyKey: "MC-537",
  },
  {
    id: "evt-13",
    timestamp: hoursAgo(2),
    agentId: "agent-amos",
    agentName: "Amos",
    agentInitials: "AM",
    eventType: "agent.task.completed",
    description: "Completed task: Write assignment endpoint tests",
    storyKey: "MC-535",
  },
  {
    id: "evt-14",
    timestamp: hoursAgo(2.3),
    agentId: "agent-naomi",
    agentName: "Naomi",
    agentInitials: "NN",
    eventType: "agent.execution.started",
    description: "Started executing MC-537",
    storyKey: "MC-537",
  },
  {
    id: "evt-15",
    timestamp: hoursAgo(2.5),
    agentId: "agent-james",
    agentName: "James",
    agentInitials: "JH",
    eventType: "agent.dispatch.failed",
    description: "Dispatch to James failed — retrying in 30 s",
    storyKey: "MC-542",
  },
  {
    id: "evt-16",
    timestamp: hoursAgo(3),
    agentId: "agent-amos",
    agentName: "Amos",
    agentInitials: "AM",
    eventType: "agent.assignment.accepted",
    description: "Amos accepted assignment for MC-535",
    storyKey: "MC-535",
  },
  {
    id: "evt-17",
    timestamp: hoursAgo(3.5),
    agentId: "agent-james",
    agentName: "James",
    agentInitials: "JH",
    eventType: "agent.watchdog.intervened",
    description: "Watchdog reset stale session for MC-538",
    storyKey: "MC-538",
  },
  {
    id: "evt-18",
    timestamp: hoursAgo(4),
    agentId: "agent-alex",
    agentName: "Alex",
    agentInitials: "AR",
    eventType: "agent.execution.started",
    description: "Started caching strategy research spike",
    storyKey: "MC-530",
  },
];

export const MOCK_ALERTS: DashboardAlert[] = [
  {
    id: "alert-01",
    severity: "error",
    title: "Dispatch failed",
    description: "MC-542 dispatch to James timed out after 3 retries",
    agentId: "agent-james",
    storyKey: "MC-542",
    timestamp: hoursAgo(2.5),
  },
  {
    id: "alert-02",
    severity: "error",
    title: "Watchdog intervention",
    description: "Stale session for MC-538 reset by watchdog",
    agentId: "agent-james",
    storyKey: "MC-538",
    timestamp: hoursAgo(3.5),
  },
  {
    id: "alert-03",
    severity: "warning",
    title: "Stale session",
    description: "Alex idle for over 45 minutes — no queued assignments",
    agentId: "agent-alex",
    storyKey: null,
    timestamp: minutesAgo(72),
  },
  {
    id: "alert-04",
    severity: "warning",
    title: "Awaiting external review",
    description: "Amos blocked on external code review for MC-535 PR #172",
    agentId: "agent-amos",
    storyKey: "MC-535",
    timestamp: minutesAgo(18),
  },
];

export const MOCK_STATS: SummaryStats = {
  storiesInProgress: 2,
  storiesQueued: 5,
  storiesBlocked: 1,
  storiesDoneToday: 3,
  tasksCompletedToday: 8,
  prsOpen: 2,
  prsAwaitingReview: 1,
  avgTaskCompletionMinutes: 23,
};
